name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build env
      run: |
        sudo apt update
        sudo apt-get -y install build-essential ccache ecj fastjar file g++ gawk gettext git java-propose-classpath libelf-dev libncurses5-dev libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget python3-distutils python3-setuptools python3-dev rsync subversion swig time xsltproc zlib1g-dev 
    - name: add submodules    
      run: |
        git submodule init
        git submodule update --depth=1
        git submodule update --remote
    - name: add feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
